name: flutter_distributor
repository: https://github.com/leanflutter/flutter_distributor

packages:
  - examples/**
  - packages/**

command:
  bootstrap:
    # Uses the pubspec_overrides.yaml instead of having Melos modifying the lock file.
    usePubspecOverrides: true

scripts:
  analyze:
    run: |
      melos exec -c 10 -- \
        flutter analyze --fatal-infos
    description: Run `flutter analyze` for all packages.

  deps:
    run: melos exec flutter pub get
    description: Run `flutter pub get` for all packages.

  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.

  format-check:
    run: melos exec dart format . --fix --set-exit-if-changed
    description: Run `dart format` checks for all packages.

  dependency_validator:
    exec: flutter pub run dependency_validator
    select-package:
      depends-on:
        - dependency_validator

  activate:
    run: melos exec --scope="flutter_distributor" -- dart pub global activate -s path .

  build_apk:
    run: melos exec --scope="hello_world" -- flutter_distributor release --name dev --jobs android-apk --skip-clean

  build_ipa:
    run: melos exec --scope="hello_world" -- flutter_distributor release --name dev --jobs ios-ipa --skip-clean
